//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public string id { get; set; }
        public string displayName1 { get; set; }
        public string displayName2 { get; set; }
        public string displayName3 { get; set; }
        public string displayName4 { get; set; }
        public string displayName5 { get; set; }
    }
}
