//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Id_MS { get; set; }
        public string Id_DD { get; set; }
        public string episodeNum { get; set; }
        public string rating { get; set; }
        public string FK_Channel { get; set; }
    }
}
